version: "3.8"

services:
  redis:
    image: "redis:alpine"
  api:
    build: .
    volumes:
      - .:/code
    command: sh -c ". entrypoint.sh"
    environment:
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_BROKER=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A ocr worker --loglevel=DEBUG -Q ocr
    environment:
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_BROKER=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    depends_on:
      - redis
      - api
  celery-beat:
    build: .
    command: celery -A ocr beat --loglevel=DEBUG
    environment:
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_BROKER=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    restart: on-failure
    depends_on:
      - redis
      - api
  flower:
    build: .
    command: flower -A ocr --port=5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - 5555:5555
    depends_on:
      - redis
      - api
      - celery

networks:
  default:
    driver: bridge