# Generated by Django 3.1.2 on 2020-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('encoded_file', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('language', models.CharField(default='pl', max_length=5)),
            ],
        ),
    ]
