# Generated by Django 2.2.4 on 2021-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
